add_newline = true
command_timeout = 1000
format = '$directory$git_branch$git_status$character'

[directory]
style = 'bold white'
truncation_length = 3

[git_branch]
format = ' [$branch]($style)'
style = 'bold red'

[git_status]
format = ' [$all_status$ahead_behind]($style)'
style = 'red'

[character]
success_symbol = '[❯](bold red)'
error_symbol = '[❯](bold red)'
